spring:
    datasource:
        url: jdbc:mysql://localhost:3306/UADF?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root

        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        
        #JPA配置
        spring.datasource.driverClassName : com.mysql.jdbc.Driver
        spring.jpa.database : MYSQL
        # Show or not log for each sql query
        spring.jpa.show-sql : true
        # Hibernate ddl auto (create, create-drop, update, validate)
        spring.jpa.properties.hibernate.hbm2ddl.auto: create
        # Naming strategy
        spring.jpa.hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # stripped before adding them to the entity manager)
        spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    http:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
